language: c
install:
  - mkdir -p deps
  - cd deps
  - git clone https://github.com/anchor/libmarquise
  - cd libmarquise
  - git checkout v2
  - ./configure && make && make check && sudo make install
  - cd ../..

script:
  - autoreconf -i
  - ./configure && make && make check
  - sudo make install
