language: c
install:
  - mkdir -p deps
  - cd deps
  - git clone https://github.com/anchor/libmarquise
  - cd libmarquise
  - autoreconf -if
  - ./configure && make && make check && sudo make install
  - cd ../..
  - sudo su -c "echo /usr/local/lib > /etc/ld.so.conf.d/local.conf"
  - sudo ldconfig

script:
  - autoreconf -if
  - ./configure && make && make check
  - sudo make install
